version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@7.0.3"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Install Chrome headless dependencies
          working_directory: /
          command: |
            apt update -qq \
            && apt install -qq -y --no-install-recommends \
            curl \
            git \
            gnupg \
            libgconf-2-4 \
            libxss1 \
            libxtst6 \
            python \
            g++ \
            build-essential \
            chromium \
            chromium-sandbox \
            dumb-init \
            fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst \
            && rm -rf /var/lib/apt/lists/* \
            && rm -rf /src/*.deb

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run the application
          command: node server.js
          background: true
      - run:
          name: Run tests
          command: npm run test