version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:15.0.1-browsers
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@7.0.3"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run the application
          command: node server.js
          background: true
      - run:
          name: Run tests
          command: npm run test